# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'overview.ui'
##
## Created by: Qt User Interface Compiler version 6.8.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QLabel, QMainWindow,
    QProgressBar, QPushButton, QSizePolicy, QSlider,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 480)
        MainWindow.setStyleSheet(u"background-color: rgb(44, 44, 44);")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.setupButton = QPushButton(self.centralwidget)
        self.setupButton.setObjectName(u"setupButton")
        self.setupButton.setGeometry(QRect(780, 0, 20, 16))
        font = QFont()
        font.setFamilies([u"Source Code Pro"])
        font.setPointSize(10)
        font.setBold(True)
        self.setupButton.setFont(font)
        self.setupButton.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.setupButton.setAutoDefault(False)
        self.setupButton.setFlat(False)
        self.line = QFrame(self.centralwidget)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(100, 0, 2, 480))
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);")
        self.line.setFrameShadow(QFrame.Shadow.Plain)
        self.line.setFrameShape(QFrame.Shape.VLine)
        self.line_2 = QFrame(self.centralwidget)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(200, 0, 2, 480))
        sizePolicy.setHeightForWidth(self.line_2.sizePolicy().hasHeightForWidth())
        self.line_2.setSizePolicy(sizePolicy)
        self.line_2.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);")
        self.line_2.setFrameShadow(QFrame.Shadow.Plain)
        self.line_2.setFrameShape(QFrame.Shape.VLine)
        self.line_3 = QFrame(self.centralwidget)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(300, 0, 2, 480))
        sizePolicy.setHeightForWidth(self.line_3.sizePolicy().hasHeightForWidth())
        self.line_3.setSizePolicy(sizePolicy)
        self.line_3.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);")
        self.line_3.setFrameShadow(QFrame.Shadow.Plain)
        self.line_3.setFrameShape(QFrame.Shape.VLine)
        self.line_4 = QFrame(self.centralwidget)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(400, 0, 2, 480))
        sizePolicy.setHeightForWidth(self.line_4.sizePolicy().hasHeightForWidth())
        self.line_4.setSizePolicy(sizePolicy)
        self.line_4.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);")
        self.line_4.setFrameShadow(QFrame.Shadow.Plain)
        self.line_4.setFrameShape(QFrame.Shape.VLine)
        self.line_5 = QFrame(self.centralwidget)
        self.line_5.setObjectName(u"line_5")
        self.line_5.setGeometry(QRect(500, 0, 2, 480))
        sizePolicy.setHeightForWidth(self.line_5.sizePolicy().hasHeightForWidth())
        self.line_5.setSizePolicy(sizePolicy)
        self.line_5.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);")
        self.line_5.setFrameShadow(QFrame.Shadow.Plain)
        self.line_5.setFrameShape(QFrame.Shape.VLine)
        self.line_6 = QFrame(self.centralwidget)
        self.line_6.setObjectName(u"line_6")
        self.line_6.setGeometry(QRect(600, 0, 2, 480))
        sizePolicy.setHeightForWidth(self.line_6.sizePolicy().hasHeightForWidth())
        self.line_6.setSizePolicy(sizePolicy)
        self.line_6.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);")
        self.line_6.setFrameShadow(QFrame.Shadow.Plain)
        self.line_6.setFrameShape(QFrame.Shape.VLine)
        self.line_7 = QFrame(self.centralwidget)
        self.line_7.setObjectName(u"line_7")
        self.line_7.setGeometry(QRect(700, 0, 2, 480))
        sizePolicy.setHeightForWidth(self.line_7.sizePolicy().hasHeightForWidth())
        self.line_7.setSizePolicy(sizePolicy)
        self.line_7.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);")
        self.line_7.setFrameShadow(QFrame.Shadow.Plain)
        self.line_7.setFrameShape(QFrame.Shape.VLine)
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 20, 80, 40))
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font1 = QFont()
        font1.setFamilies([u"Source Code Pro"])
        font1.setBold(True)
        self.label.setFont(font1)
        self.label.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.Fader2 = QSlider(self.centralwidget)
        self.Fader2.setObjectName(u"Fader2")
        self.Fader2.setGeometry(QRect(142, 395, 16, 71))
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Expanding)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.Fader2.sizePolicy().hasHeightForWidth())
        self.Fader2.setSizePolicy(sizePolicy1)
        self.Fader2.setMinimum(-70)
        self.Fader2.setMaximum(10)
        self.Fader2.setValue(-70)
        self.Fader2.setOrientation(Qt.Orientation.Vertical)
        self.levelBar2 = QProgressBar(self.centralwidget)
        self.levelBar2.setObjectName(u"levelBar2")
        self.levelBar2.setGeometry(QRect(145, 295, 8, 100))
        sizePolicy.setHeightForWidth(self.levelBar2.sizePolicy().hasHeightForWidth())
        self.levelBar2.setSizePolicy(sizePolicy)
        self.levelBar2.setValue(24)
        self.levelBar2.setOrientation(Qt.Orientation.Vertical)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(110, 20, 80, 40))
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setFont(font1)
        self.label_2.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(210, 20, 80, 40))
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setFont(font1)
        self.label_3.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_3.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(310, 20, 80, 40))
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setFont(font1)
        self.label_4.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_4.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(410, 20, 80, 40))
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setFont(font1)
        self.label_5.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_5.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(510, 20, 80, 40))
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setFont(font1)
        self.label_6.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_6.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(610, 20, 80, 40))
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setFont(font1)
        self.label_7.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_7.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(710, 20, 80, 40))
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setFont(font1)
        self.label_8.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_8.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.Fader1 = QSlider(self.centralwidget)
        self.Fader1.setObjectName(u"Fader1")
        self.Fader1.setGeometry(QRect(35, 395, 20, 71))
        self.Fader1.setMinimum(-70)
        self.Fader1.setMaximum(10)
        self.Fader1.setValue(-70)
        self.Fader1.setOrientation(Qt.Orientation.Vertical)
        self.levelBar1 = QProgressBar(self.centralwidget)
        self.levelBar1.setObjectName(u"levelBar1")
        self.levelBar1.setGeometry(QRect(40, 295, 8, 100))
        sizePolicy.setHeightForWidth(self.levelBar1.sizePolicy().hasHeightForWidth())
        self.levelBar1.setSizePolicy(sizePolicy)
        self.levelBar1.setMinimum(-90400)
        self.levelBar1.setMaximum(0)
        self.levelBar1.setValue(-90400)
        self.levelBar1.setOrientation(Qt.Orientation.Vertical)
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(20, 270, 49, 16))
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_10 = QLabel(self.centralwidget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(124, 270, 49, 16))
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.Fader3 = QSlider(self.centralwidget)
        self.Fader3.setObjectName(u"Fader3")
        self.Fader3.setGeometry(QRect(243, 395, 16, 71))
        sizePolicy1.setHeightForWidth(self.Fader3.sizePolicy().hasHeightForWidth())
        self.Fader3.setSizePolicy(sizePolicy1)
        self.Fader3.setMinimum(-70)
        self.Fader3.setMaximum(10)
        self.Fader3.setValue(-70)
        self.Fader3.setOrientation(Qt.Orientation.Vertical)
        self.levelBar3 = QProgressBar(self.centralwidget)
        self.levelBar3.setObjectName(u"levelBar3")
        self.levelBar3.setGeometry(QRect(246, 295, 8, 100))
        sizePolicy.setHeightForWidth(self.levelBar3.sizePolicy().hasHeightForWidth())
        self.levelBar3.setSizePolicy(sizePolicy)
        self.levelBar3.setValue(24)
        self.levelBar3.setOrientation(Qt.Orientation.Vertical)
        self.label_11 = QLabel(self.centralwidget)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(225, 270, 49, 16))
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setAlignment(Qt.AlignmentFlag.AlignCenter)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.setupButton.setDefault(False)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.setupButton.setText(QCoreApplication.translate("MainWindow", u"S", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"NAME", None))
        self.levelBar2.setFormat("")
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"NAME", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"NAME", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"NAME", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"NAME", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"NAME", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"NAME", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"NAME", None))
        self.levelBar1.setFormat("")
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Level", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Level", None))
        self.levelBar3.setFormat("")
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Level", None))
    # retranslateUi

